export const LOG_EVENTS = {
  // HTTP
  HTTP_RESPONSE_OUT: 'HTTP_RESPONSE_OUT',
  HTTP_REQUEST_IN: 'HTTP_REQUEST_IN',
  HTTP_ERROR: 'HTTP_ERROR',

  // SYSTEM
  SYSTEM_INVALID_INPUT: 'SYSTEM_INVALID_INPUT',
  APPLICATION_STARTUP: 'APPLICATION_STARTUP',
  APPLICATION_ERROR: 'APPLICATION_ERROR',
  SYSTEM_DB_ERROR: 'SYSTEM_DB_ERROR',

  // WS
  WS_CONNECTION: 'WS_CONNECTION',
  WS_DISCONNECTION: 'WS_DISCONNECTION',
  WS_USER_CONNECTION: 'WS_USER_CONNECTION',
  WS_JOIN_ROOM: 'WS_JOIN_ROOM',
  WS_AUTH_ERROR: 'WS_AUTH_ERROR',

  // BACKGROUND JOBS
  BACKGROUND_JOB_COMPLETED: 'BACKGROUND_JOB_COMPLETED',
  BACKGROUND_JOB_STARTED: 'BACKGROUND_JOB_STARTED',
  BACKGROUND_JOB_FAILED: 'BACKGROUND_JOB_FAILED',
  UNKNOWN_JOB_NAME: 'UNKNOWN_JOB_NAME',

  // EXCEPTION
  EXCEPTION: 'EXCEPTION',

  // RETRY
  RETRY_ATTEMPT_FAILED: 'RETRY_ATTEMPT_FAILED',
  RETRY_EXHAUSTED: 'RETRY_EXHAUSTED',

  // NOTIFICATIONS
  NOTIFICATION_DISPATCHED: 'NOTIFICATION_DISPATCHED',
  NOTIFICATION_DISPATCH_FAILED: 'NOTIFICATION_DISPATCH_FAILED',

  // USER
  USER_REGISTRATION_FAILED: 'USER_REGISTRATION_FAILED',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
  USER_ACCESS_DENIED: 'USER_ACCESS_DENIED',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',

  // AUTH
  AUTH_PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_BLACKLISTED_TOKEN_REUSE: 'AUTH_BLACKLISTED_TOKEN_REUSE',
  AUTH_REFRESH_TOKEN_ROTATED: 'AUTH_REFRESH_TOKEN_ROTATED',
  AUTH_REFRESH_TOKEN_REUSE: 'AUTH_REFRESH_TOKEN_REUSE',
  AUTH_2FA_DISABLED_FAILED: 'AUTH_2FA_DISABLED_FAILED',
  AUTH_2FA_RECOVERY_FAILED: 'AUTH_2FA_RECOVERY_FAILED',
  AUTH_2FA_RECOVERY_USED: 'AUTH_2FA_RECOVERY_USED',
  AUTH_TOKEN_BLACKLISTED: 'AUTH_TOKEN_BLACKLISTED',
  AUTH_SESSION_EVICTED: 'AUTH_SESSION_EVICTED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  AUTH_EMAIL_VERIFIED: 'AUTH_EMAIL_VERIFIED',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_2FA_CHALLENGE: 'AUTH_2FA_CHALLENGE',
  AUTH_2FA_DISABLED: 'AUTH_2FA_DISABLED',
  AUTH_2FA_ENABLED: 'AUTH_2FA_ENABLED',
  AUTH_2FA_SUCCESS: 'AUTH_2FA_SUCCESS',
  AUTH_2FA_FAILED: 'AUTH_2FA_FAILED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  // SESSION
  SESSION_UPDATE_FAILED: 'SESSION_UPDATE_FAILED',
  SESSION_REVOKED_ALL: 'SESSION_REVOKED_ALL',
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_DELETED: 'SESSION_DELETED',

  // ENCRYPTION & DECRYPTION
  INVALID_ENCRYPTION_PAYLOAD: 'INVALID_ENCRYPTION_PAYLOAD',
  ENCRYPTION_FAILURE: 'ENCRYPTION_FAILURE',
  ENCRYPTION_SUCCESS: 'ENCRYPTION_SUCCESS',
  DECRYPTION_FAILURE: 'DECRYPTION_FAILURE',
  DECRYPTION_SUCCESS: 'DECRYPTION_SUCCESS',

  // MAIL
  WELCOME_EMAIL_SENT: 'WELCOME_EMAIL_SENT',
  PASSWORD_RESET_EMAIL_SENT: 'PASSWORD_RESET_EMAIL_SENT',
  VERIFICATION_EMAIL_SENT: 'VERIFICATION_EMAIL_SENT',
  EMAIL_SEND_FAILURE: 'EMAIL_SEND_FAILURE',
} as const;

export type LogEvent = keyof typeof LOG_EVENTS;
