#!/bin/sh

echo "🔍 Running ESLint..."
pnpm run lint

echo "✨ Checking code formatting..."
pnpm run format:check

echo "📝 Running Type Check..."
pnpm run type-check

echo "✅ All checks passed! Pushing..."